"""Connection presets contain public configuration only, never credentials."""

PROVIDER_PRESETS = {
    'deepseek': {
        'label': 'DeepSeek (Official)',
        'alias': 'deepseek',
        'adapter': 'openai',
        'base_url': 'https://api.deepseek.com',
        'models': ['deepseek-flash', 'deepseek-chat', 'deepseek-reasoner'],
        'note': 'Direct DeepSeek API. Supports DeepSeek-V4.1-Flash (deepseek-flash), DeepSeek-V3 (chat) and DeepSeek-R1 (reasoner).',
        'key_url': 'https://platform.deepseek.com/api_keys',
    },
    'qwen': {
        'label': 'Alibaba Qwen (DashScope)',
        'alias': 'qwen',
        'adapter': 'openai',
        'base_url': 'https://dashscope.aliyuncs.com/compatible-mode/v1',
        'models': [
            'qwen-max',
            'qwen-plus',
            'qwen-turbo',
            'qwen2.5-72b-instruct',
            'qwen2.5-coder-32b-instruct',
            'qwen2.5-coder-7b-instruct',
            'qvq-72b-preview',
        ],
        'note': 'Alibaba DashScope OpenAI-compatible endpoint. Access to Qwen 2.5, Qwen-Max, and Qwen-Coder models.',
        'key_url': 'https://dashscope.console.aliyun.com/apiKey',
    },
    'minimax': {
        'label': 'MiniMax API',
        'alias': 'minimax',
        'adapter': 'openai',
        'base_url': 'https://api.minimax.chat/v1',
        'models': [
            'MiniMax-Text-01',
            'abab6.5s-chat',
            'abab6.5t-chat',
            'abab5.5-chat',
        ],
        'note': 'MiniMax large-context foundation models, including MiniMax-Text-01 with up to 4M context.',
        'key_url': 'https://platform.minimaxi.com/user-center/basic-information/interface-key',
    },
    'moonshot': {
        'label': 'Moonshot AI (Kimi)',
        'alias': 'moonshot',
        'adapter': 'openai',
        'base_url': 'https://api.moonshot.cn/v1',
        'models': [
            'moonshot-v1-8k',
            'moonshot-v1-32k',
            'moonshot-v1-128k',
            'moonshot-v1-auto',
            'kimi-latest',
        ],
        'note': 'Moonshot AI / Kimi long-context conversational models with tool-calling capabilities.',
        'key_url': 'https://platform.moonshot.cn/console/api-keys',
    },
    'siliconflow': {
        'label': 'SiliconFlow (SiliconCloud)',
        'alias': 'siliconflow',
        'adapter': 'openai',
        'base_url': 'https://api.siliconflow.cn/v1',
        'models': [
            'deepseek-ai/DeepSeek-V3',
            'deepseek-ai/DeepSeek-R1',
            'Qwen/Qwen2.5-72B-Instruct',
            'Qwen/Qwen2.5-Coder-32B-Instruct',
            'THUDM/glm-4-9b-chat',
        ],
        'note': 'Fast inference for open-weights models (DeepSeek-V3, DeepSeek-R1, Qwen2.5, GLM-4).',
        'key_url': 'https://cloud.siliconflow.cn/account/ak',
    },
    'openrouter': {
        'label': 'OpenRouter (200+ Models Aggregator)',
        'alias': 'openrouter',
        'adapter': 'openrouter',
        'base_url': 'https://openrouter.ai/api/v1',
        'models': [
            'deepseek/deepseek-r1',
            'deepseek/deepseek-chat',
            'qwen/qwen-2.5-72b-instruct',
            'qwen/qwen-2.5-coder-32b-instruct',
            'minimax/minimax-01',
            'moonshotai/moonshot-v1-32k',
            'anthropic/claude-3.7-sonnet',
            'openai/gpt-4o',
            'meta-llama/llama-3.3-70b-instruct',
        ],
        'note': 'Universal API routing to DeepSeek, Qwen, MiniMax, Kimi, Claude, GPT, and 200+ models with a single balance.',
        'key_url': 'https://openrouter.ai/keys',
    },
    'zai': {
        'label': 'GLM / Z.ai API',
        'alias': 'zai',
        'adapter': 'openai',
        'base_url': 'https://api.z.ai/api/coding/paas/v4',
        'models': ['glm-5.3', 'glm-4.7', 'GLM-5.3-Flash'],
        'note': 'Uses your Z.ai Coding Plan API key and quota. Supports GLM-4 and GLM-5 series.',
        'key_url': 'https://z.ai/manage-apikey/apikey-list',
    },
    'gemini': {
        'label': 'Google Gemini API key',
        'alias': 'gemini',
        'adapter': 'gemini',
        'base_url': '',
        'models': [
            'gemini-2.5-pro',
            'gemini-2.5-flash',
            'gemini-2.0-flash-thinking-exp-01-21',
        ],
        'note': 'Uses a Gemini API key. For your Google AI subscription, use Gemini — Google account above.',
        'key_url': 'https://aistudio.google.com/apikey',
    },
    'anthropic': {
        'label': 'Anthropic (Claude API)',
        'alias': 'anthropic',
        'adapter': 'anthropic',
        'base_url': '',
        'models': [
            'claude-3-7-sonnet-20250219',
            'claude-3-5-sonnet-20241022',
            'claude-3-5-haiku-20241022',
        ],
        'note': 'Official Anthropic Claude API key with support for extended thinking.',
        'key_url': 'https://console.anthropic.com/settings/keys',
    },
    'openai': {
        'label': 'OpenAI API',
        'alias': 'openai',
        'adapter': 'openai',
        'base_url': 'https://api.openai.com/v1',
        'models': [
            'gpt-4o',
            'gpt-4o-mini',
            'o1',
            'o3-mini',
        ],
        'note': 'Official OpenAI API key. Supports reasoning models (o1, o3-mini) and multimodal models.',
        'key_url': 'https://platform.openai.com/api-keys',
    },
    'groq': {
        'label': 'Groq (Ultra-Fast LPU)',
        'alias': 'groq',
        'adapter': 'groq',
        'base_url': 'https://api.groq.com/openai/v1',
        'models': [
            'deepseek-r1-distill-llama-70b',
            'llama-3.3-70b-versatile',
            'qwen-2.5-32b',
        ],
        'note': 'Ultra-fast inference powered by Groq LPU hardware.',
        'key_url': 'https://console.groq.com/keys',
    },
    'together': {
        'label': 'Together AI',
        'alias': 'together',
        'adapter': 'openai',
        'base_url': 'https://api.together.xyz/v1',
        'models': [
            'deepseek-ai/DeepSeek-R1',
            'deepseek-ai/DeepSeek-V3',
            'Qwen/Qwen2.5-72B-Instruct-Turbo',
            'Qwen/Qwen2.5-Coder-32B-Instruct',
        ],
        'note': 'Fast cloud inference platform for open models.',
        'key_url': 'https://api.together.ai/settings/api-keys',
    },
    'mistral': {
        'label': 'Mistral AI',
        'alias': 'mistral',
        'adapter': 'openai',
        'base_url': 'https://api.mistral.ai/v1',
        'models': [
            'mistral-large-latest',
            'codestral-latest',
            'mistral-small-latest',
        ],
        'note': 'Official Mistral API for Mistral Large and Codestral.',
        'key_url': 'https://console.mistral.ai/api-keys',
    },
    'ollama': {
        'label': 'Ollama (Local Offline)',
        'alias': 'ollama',
        'adapter': 'ollama_chat',
        'base_url': 'http://localhost:11434',
        'models': [
            'deepseek-r1:14b',
            'deepseek-r1:8b',
            'qwen2.5:14b',
            'qwen2.5-coder:14b',
            'qwen2.5-coder:32b',
            'llama3.3:70b',
        ],
        'note': 'Local models running via Ollama on your machine. Zero cost, no external API keys required.',
        'key_url': 'https://ollama.com',
    },
}
